meta_name: "BonneFeuille"
meta_title: "BonneFeuille - Rencontrez l'amour vert"
meta_description: "Votre paysagiste de poche pour vous aider à créer et entretenir votre jardin citadin!"
meta_image: "Logo_BonneFeuille_ipad_air.png" # should exist in `app/assets/images/`
twitter_account: "@NicolasBourdin3"   # required for Twitter Cards
