# Il s'agit d'un fichier YAML désérialisé en un hash qui indique quelles tâches doivent être planifiées, et à quel
# rythme. En ce moment, le timing est une mise à jour tous les jours à 4 heures du mat (Sidekiq est en retard de deux
# heures par rapport à l'heure française).
retrieve_gardens:
      cron: '00 02 * * *'
      class: 'RetrieveGardensJob'
