:concurrency: 3
:timeout: 25
:verbose: true
:queues:
  # Queue priority:
  # https://github.com/mperham/sidekiq/wiki/Advanced-Options
  # https://mikerogers.io/2019/06/06/rails-6-sidekiq-queues
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge

# Le code qui suit est sans doute à retirer au vu du changement de sidekiq-scheduler a sidekiq-cron.
:scheduler:
  :schedule:
    retrieve_gardens:
      cron: '0 6 * * *'
      class: RetrieveGardensJob
